[package]
authors = ["mrdotb <mrdotb@protonmail.com>"]
edition = "2018"
name = "uds"
version = "0.1.0"

[dependencies]
base64 = "0.10.1"
curl = "0.4.0"
oauth2 = "2.0.0-beta.2"
rand = "0.6.5"
reqwest = "0.9.17"
serde = "1.0"
serde_json = "1.0"
url = "1.7.2"
